version: "3"
services:
  apache:
    build: .
    ports:
      - "8000:80"
    links:
      - mysql
    env_file: .env
    volumes:
      - ./app:/var/www/html/

  mysql:
    image: mysql:5
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"

